<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <Folder Include="obj\" />
      <Folder Include="UseCases\PlaceUseCases\Create\" />
      <Folder Include="UseCases\ReservationUseCases\Delete\" />
    </ItemGroup>

    <ItemGroup>
      <Compile Remove="obj\Debug\**" />
    </ItemGroup>

    <ItemGroup>
      <EmbeddedResource Remove="obj\Debug\**" />
    </ItemGroup>

    <ItemGroup>
      <None Remove="obj\Debug\**" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.8" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.8">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
    </ItemGroup>

</Project>
